apiVersion: v1
data:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:QZNTvlAvvwnP/VSd,iv:Q25fws60xPwxdBLo3EmESYWT7ps30DCo4wAHiFq7hNw=,tag:CIHSCZUQnJce7j3FSQJEvg==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:6m6euldxU3X9FBydhjxolUQNXtEpPBE14Lu4C1rsGgW/21Opcy2n06gNFGn4a86jp3EXcRuI/52jjMk3/ee0dg==,iv:0jaObpKF9BE7QP/Y7+kv4e+qHoSqljMW1B0x5kkE/Aw=,tag:ukpqRX3TdzYr3gEPADtlWQ==,type:str]
kind: Secret
metadata:
    name: rustfs
    namespace: rustfs
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TTBrNnIrSDM2cDA3cERQ
            SjFhcmVFTEFmTnhGV3BpcDJYcFZXdHFYV0NvCnlheHZIS1ZWa3F6TEowUCtPWVov
            UWFoekwxaHo0dFBnLzdhN2Z1ekgweE0KLS0tIEpGSmp3djA0K0llRFBHblNxWlNv
            NVNORmJsRDVtN1QwVmVYTTc0S2s0cGcKFUEuo61zJt6CBxO+yLe/rFWm2WEvQp5Q
            14wyOpVmBAKHZbi0TmlPoGDM5JM3b877swzzq03sGNZu/2KsSe/Q7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14d8ta7ch7n4jnx096fnvlmvqmvvzzaty7sf6vmrlcyq25h8439fs5328xk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T11:29:12Z"
    mac: ENC[AES256_GCM,data:A7lVurp24TZoO9nrkT9IM/Ez9xa4XKXUq7yCInnSsJg9pYdm5lQJCMkj5APnTq/GUS1FrImWFCwt8ZbTMszR3KrpDUkavc7X6J2hKtF1hMCUrjddYifORqcsn/+4q/GFTjBn5MJJQe9GeEyxyYoDdt0G2/e3SoII7EUNWz5uOnY=,iv:7fxREE7i11Lw6nCCz1LSFrF0F7IRIhUJa59GqoFGpZE=,tag:boiL4iUpkNJ+JLyUdWl9GA==,type:str]
    version: 3.13.3
