apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudpoc.fullname" . }}-backend
  labels:
    {{- include "cloudpoc.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "cloudpoc.selectorLabels" (dict "ctx" $ "component" "backend") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
