apiVersion: v1
data:
    APP_SECRET: ENC[AES256_GCM,data:rG4l/o+ZLKXNgnKI7aaUdwuxCsRtyPjy0JpToEGPSChC9Ug8hatTCy8lwli4kF6t/hBi/EJVlNRb8Dja1Tk2s62pitWSD11/rl+Fa//ZdlidEjpWQvbeKw==,iv:TFLRpLyceLajEo8YKA/nU7NpT/iDcYFSF2xmsarIWq4=,tag://kO84FNuqm+PBOzOy7ucg==,type:str]
kind: Secret
metadata:
    name: cloudpoc-backend
    namespace: staging
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeWFSTDR2VC9lbStqQThJ
            dUl3aTZXNFo1MGNsNXFMZlNPMlpBMytvZlRBCmRObEl6WE9GTDdYMlBUeW5WN3FY
            YU1rTlJZR0RMV1VqOE5heTBkVWg1WTQKLS0tIGJib1ltR0UwUzhWM1BTdWZpNERh
            NXA2SkpMQXRleFVubGszb2tydXQwY1UKYjQVADM/qWJDnbsc8oU2t17NaHzZn9Ul
            mgsxSHsXDN40U3BCPMLbYS/DCMoj84vPRJgs2SkfqS97BY13YFmvBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14d8ta7ch7n4jnx096fnvlmvqmvvzzaty7sf6vmrlcyq25h8439fs5328xk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T16:37:37Z"
    mac: ENC[AES256_GCM,data:zQ16OmbOeailAUt+puCknWLDebE/5vOfMKPuPBtlNUxRNLoTEcD4yqPzi4CWlEli8gmTEZl22EPyQYdDLQfGN7/yWQYie8hrVNB/qbbLd7XJEryFS+vo/LI7IifqQW0zSW8tGRu/ojVRUY993raBJ8lWcIGxirQtGXcVoHQZxWg=,iv:5LVKphmAXxgFL8NlIXJ3cWXr9lrZisTt/oeEHl2TLw0=,tag:3hPHDsqihs8vcXRogBj1Pg==,type:str]
    version: 3.13.3
