apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:UmsianKYFan9BkzQ,iv:j55vJ6XTf5BKoNvN+azwW61tCbiD6Z5X5jx0SCPtjV4=,tag:KmCpkJm/Vl+yuYNvLqiSLw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:bYN6Fmv+KJeZLKO7jEXDw71jA8EYaHo31IwwTWqKxg7+Njium9d4vAV7Xeq3W6Un73+V8nnsv/hJHczByk31tw==,iv:fR4cJCLJjBJG0DBE6gur4QfvsokSRu3o02XZSLGSG8c=,tag:8ukdNsvDuOcFkU652xPIBA==,type:str]
kind: Secret
metadata:
    name: cloudpoc-s3
    namespace: cloudpoc-staging
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRXNCalByeFVLTENsN3JX
            eXA1dTJiTU5qNStUdGNyN0pvdHlqRkZkN2dNCktnNlhOSVFpb1pmNVlucGtzNnRY
            ak1DZkMwZ2hVT2pDTW1Gc2g2Q0FmQzgKLS0tIFlsRGIvQTVGclFwZnMvQ3ZHT1RN
            a3E2SW5uYXJqOC8rczFJSFNTM05mencKQ+j4j+oxfrZ7KdVeIMzXS2e5jTZGxBqR
            LJ5LiyT0VkJp6kpCyiuubIxHz8zvruebvKLJA+RZkGbfkxwonRwNcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14d8ta7ch7n4jnx096fnvlmvqmvvzzaty7sf6vmrlcyq25h8439fs5328xk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3amZxQXQvNDVGTjdvVXhk
            NkVVNERKRnV4dXJ2eFRGc2RwZ0k3WXZRbURJClJYbEhad1N1MXc4OHRhcmFBKzlJ
            REljREtZTlVKMEZUYjg4TVZBWUZnZncKLS0tICt0VHZyUFZGN3hMTzZuVmxOOVZH
            dFFvMG1ZTklraldCRUV2ZGNqU2hVK1EKenITyleE2jQ6t360LyihlMrH9ba1en1D
            +d64f58VEMkrm6uko1/8kWRepKzRiQyW54K2+VGgYT2I9YBAherOHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wau5d4yyqjxhxlx3w6d0ygr5trfgww4z2p72n560l9tdyvmgscwq0h8q95
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T11:34:24Z"
    mac: ENC[AES256_GCM,data:7DrNEBboq2w/B9HzB17X/WcbbGLur2RY2ZO5sjE2TfK4ZJvVmeq8Zf8ozPVG+0f5SA1z3MA2LwumKKq7yOiAGQuV++MP3iYCemQuTMiM4G7tZjsOSR0mFjCYtTl1Z9Er9ifoUJjS+aDi8Pgj4QQHQElwWIoY7Waws+salLFOagE=,iv:d460C+7wdSdjNDuS5os7kf5VzkCQ52tK8+a4UEJhpMs=,tag:slJEWx9KaqIdGMW66Ju4Rw==,type:str]
    version: 3.13.3
