apiVersion: v1
data:
    APP_SECRET: ENC[AES256_GCM,data:rG4l/o+ZLKXNgnKI7aaUdwuxCsRtyPjy0JpToEGPSChC9Ug8hatTCy8lwli4kF6t/hBi/EJVlNRb8Dja1Tk2s62pitWSD11/rl+Fa//ZdlidEjpWQvbeKw==,iv:TFLRpLyceLajEo8YKA/nU7NpT/iDcYFSF2xmsarIWq4=,tag://kO84FNuqm+PBOzOy7ucg==,type:str]
kind: Secret
metadata:
    name: cloudpoc-backend
    namespace: cloudpoc-staging
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDL0RaOS8wNnlOb2xxZUU1
            NllyUEVrTlZJNFZ2ZVVwenQraVFrSGp3ZkI4CmdRNGRPRVU5eklidW5acHRkYnlu
            NERHQ2xWQlc1ZzA3cHY0QjNFRTJmSWMKLS0tIEFmV2xjdjBDVWg5UnBOcHo0Sk5m
            K2RmaHVGQkU0aFpYaXVwZXdBTUNBTU0Kqy6uNkEZPzpselowQ9yu+kJ9ofIN/d7i
            Mw1cmj78QORSAbV3ioreH4Y4p8Q+jc+5WgAWwxlTLjAJCW9HDT7TPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14d8ta7ch7n4jnx096fnvlmvqmvvzzaty7sf6vmrlcyq25h8439fs5328xk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQXhHeHAybFhlY2JsN1M3
            RWlYdFRPbElBK2p2R0R1dElOTXQwVUxOZUhNCmVNWWVqNHJxUFlua0tXZTRqUkI3
            NGtYZm9UZXJVMU5XUFNobjlMckhBNG8KLS0tIGlJUWZSMmhHekNjbVV4c1FmalBN
            NFdHUmI1MmI2d1BEQmxvbDI3cm9iUU0KM5CMH+cn46o9qGbEsNV/yVeDngmcMazi
            BUHDl6bb1imw64R/sm+WWlL3mOot3q4hYwVj8UZ2FC5fOLVNqL481w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wau5d4yyqjxhxlx3w6d0ygr5trfgww4z2p72n560l9tdyvmgscwq0h8q95
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T08:31:52Z"
    mac: ENC[AES256_GCM,data:Vip5cuUUHS1RJqgeoKO/SVi/7F+vf6ji7o1ofaTk/u4K/l/sADAMViUk2ZcELWvzVukf+r+zBC0UDqizctgecj+40GRVZn8saUOZjwXUG5X839MM8PJciPpiZ3+g94TD+Iqslh7jPJ+Cf6jbruvFavDfYxsRKrIJeit+Psrto0o=,iv:8j111XiRbZnV0VT3HmhveV4hNcH/rOeXQmgXC5tmEmM=,tag:dlFKgPSVJjfTGErR/SmAqg==,type:str]
    version: 3.13.3
