apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:NH3StD+gK7IxBHv9t4tIxHYBbScGxL7QsUufWva6kWR/QVSc9w942h2km/LdpIXiyKMlCKwzW3RXn47yaxXvObHbxeiTrEafuqrb15uD9Mt/VCVOTodQKY8ZHZ7+BuF6SG8MyU55SCWiJXk7UmE8x79YBeEAz3q18A1z44vf5OB2hAoiOL424/AT3wa4fq5Sbtw2k4TySlKzSyk1qRO659VrNkGru6USqRZgqoZb/J/XmqAIFz5pR2lQuu1HGZ9+UfWoE6JVnNWU6Q4ihGsFhZzlw2Q1l894D1jtE84IoIyE7vrE+CL9rErMwRX7qgoDbAvQJDqMLA8=,iv:8lv2QUb1QJsKj2uWDhMPSHNLhE3AkK54NvnOrgfiOtI=,tag:dLgHH5QvXEuX/cMD5zbtBg==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: cloudpoc-staging
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaTFyQmxxbjFibWVWQ2gy
            b3dtV2ovTGpUS3Jxa3dCUXY0NTNoMy9qazAwClpOdkowcjhUVi8rSWwrS2Q5K29K
            NXB1VkQ0eUxPRkpTRkMzMEI2aXVpVmsKLS0tIFJHaGZHbXJzMUFlYkUzaUcvU0ZR
            OUh4VWIvcnZxMHBaT0d3UHpmWlVhMWsKdqNEAij/TUXwjHZBtfwRFckwefbCbKkA
            8xaleJ7yCp3HeLicPXKUVWCjbHjd/jeKbnL2GA+6w5su7lwuSG8nVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14d8ta7ch7n4jnx096fnvlmvqmvvzzaty7sf6vmrlcyq25h8439fs5328xk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdEtKQUxGYzIzaXgxVyt4
            UUxyUDJRd1RmRDVzSVFxNk5EV013MW0zYld3ClZDSFFObElCc1RKSSsrT3ZDeUU0
            RWxSbHE2TWlabncyWnVDYUJsV1FNL00KLS0tIHA2Q29kb3pGcXJlRkV6dVBrSk53
            ZjJFd1lOM1dROXk0c2l5MVBaVU5yOEUKmVOTWlXtovDobQRx5eGmWTI3csWK/GDY
            lUy8Hxi4uyOSLrm2Iiw3EKKsImLYzhZcTVmSI0HtjpubHQT5uOLPzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wau5d4yyqjxhxlx3w6d0ygr5trfgww4z2p72n560l9tdyvmgscwq0h8q95
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T08:32:03Z"
    mac: ENC[AES256_GCM,data:YOhl5gbk2S9JmtHJDXiGhnLEPFUXVR5aA7teLGNfzPEq8vGyXR4vF/vY9JHN72CgYZgzwV/j12TetZcxbdVG7ISPe7Hl/K46qobJ7WC82UNH4KQLaO5WKbK3lzipw9xhqFyCZTZz7617vsNUTrFP09eWVmiJIv2+zzB43HtbxaI=,iv:fS7c3Cw57k7Aj1vZulRwi9zorKoKIV8TZYPwvTjxr1U=,tag:ekZOOvCO63WjI41Ltu2oGw==,type:str]
    version: 3.13.3
