apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:NH3StD+gK7IxBHv9t4tIxHYBbScGxL7QsUufWva6kWR/QVSc9w942h2km/LdpIXiyKMlCKwzW3RXn47yaxXvObHbxeiTrEafuqrb15uD9Mt/VCVOTodQKY8ZHZ7+BuF6SG8MyU55SCWiJXk7UmE8x79YBeEAz3q18A1z44vf5OB2hAoiOL424/AT3wa4fq5Sbtw2k4TySlKzSyk1qRO659VrNkGru6USqRZgqoZb/J/XmqAIFz5pR2lQuu1HGZ9+UfWoE6JVnNWU6Q4ihGsFhZzlw2Q1l894D1jtE84IoIyE7vrE+CL9rErMwRX7qgoDbAvQJDqMLA8=,iv:8lv2QUb1QJsKj2uWDhMPSHNLhE3AkK54NvnOrgfiOtI=,tag:dLgHH5QvXEuX/cMD5zbtBg==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: cloudpoc-staging
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeEZITmVqT2NrWXFKMTkr
            ZHRJcHpnQnNtVHA2OXRuRGErcXhEWkVMSERzCnhicXpEZ1dMdTEwMU0xTFZ5WEpU
            dU1aQWF0RndTRnRWdmJubnVMckJrdGcKLS0tIElRSHVsOEdlWWdadWdyUDJodmMr
            c1dzeitNNmZqaUFpUko5c0hSeklqcEUKeOfe9CYYZE1mDIIED7Xe5gutKRVwU56s
            nIKyRNGNgSC5SQGMnBVtpRoy37Z9uM7OBB36x7FT7F9YZLWvScBNpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14d8ta7ch7n4jnx096fnvlmvqmvvzzaty7sf6vmrlcyq25h8439fs5328xk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T08:32:03Z"
    mac: ENC[AES256_GCM,data:YOhl5gbk2S9JmtHJDXiGhnLEPFUXVR5aA7teLGNfzPEq8vGyXR4vF/vY9JHN72CgYZgzwV/j12TetZcxbdVG7ISPe7Hl/K46qobJ7WC82UNH4KQLaO5WKbK3lzipw9xhqFyCZTZz7617vsNUTrFP09eWVmiJIv2+zzB43HtbxaI=,iv:fS7c3Cw57k7Aj1vZulRwi9zorKoKIV8TZYPwvTjxr1U=,tag:ekZOOvCO63WjI41Ltu2oGw==,type:str]
    version: 3.13.3
